apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rave-ci-arc-controller-test-cheng
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rave
  destination:
    name: in-cluster
    namespace: test-cheng
  source:
    path: .
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    targetRevision: 0.12.1
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            fullnameOverride: arc-controller
            flags:
              watchSingleNamespace: test-cheng