name: 'Checkout Files by Github Api'
description: "Checkout Files by Github Api"
inputs:
  out-directory:
    description: Out directory
    required: false
    default: "."
  paths:
    description: Checkout files/folders
    required: true
  github-token:
    description: Github token
    required: true
runs:
  using: "composite"
  steps:
    - name: Check the manifest file if cyclops tags exist
      id: check-manifest
      shell: pwsh
      run: |
        Import-Module ${{ github.action_path }}/functions.psm1
        $files = "${{ inputs.paths }}" -split '\r?\n' | Where-Object {-not [string]::IsNullOrWhitespace($_) }
        $files
        $files.Count
        Get-files -Repository "mdsol/RaveEDC" -Paths $files -OutDirectory "${{ inputs.out-directory }}" -GithubToken ${{ inputs.github-token }}