name: Cerebro Deployment
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: false
        type: string
        default: sandbox
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Show secrets
        run: Write-Host $Env:var0
        shell: pwsh
        env:
          var0 : ${{ secrets.secret0 }}
