name: Test PR

on:
  pull_request:
  issue_comment:
    types: [created]
jobs:
  test-trigger:
    name: Start Runner and hang
    runs-on: ubuntu-latest
    steps:
      - name: Test0
        if: (github.event_name == 'pull_request' || (github.event.issue.pull_request && contains(github.event.comment.body, '/e2e')) && contains(github.event.pull_request.labels.*.name, 'need e2e'))
        run: |
          if ("${{ github.event_name }}" -eq "pull_request")
          {
            Write-Host "Labels: ${{ toJson(github.event.pull_request.labels) }}"
          }
          if ("${{ github.event_name }}" -eq "issue_comment") 
          {
            Write-Host "Comment Body: ${{ github.event.comment.body }}"
            Write-Host "0"
            Write-Host "gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }} -X PATCH -f body='You requested E2E testing.'"
            Write-Host "1"
            gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }} -X PATCH -f body='You requested E2E testing.'
            Write-Host "2"
          }
          
        shell: pwsh
