name: Test PR

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AAA: bbb

    steps:
      - name: Override
        shell: pwsh
        run: |
          "AAA=ccc" | Add-Content $GITHUB_ENV

      - name: Show
        shell: bash
        run: |
          echo $AAA
