
name: "Try labeled"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: try
        run: |
          Write-Host "env.INPUTS_RAVE_DB_REF2 = $env:INPUTS_RAVE_DB_REF2"
        shell: pwsh
        env:
          INPUTS_RAVE_DB_REF2: ${{ env.INPUTS_RAVE_DB_REF }}
          INPUTS_RAVE_DB_REF: ${{ inputs.rave-db-ref }}
