
name: "Try"
on:
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
      yaml:
        description: 'yaml'
        required: false
        type: string
      stage:
        description: 'stage'
        required: false
        type: string
        default: main

jobs:
  job1:
    environment: distro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npm install -g md-to-pdf
          md-to-pdf --md-file-encoding UTF8 --pdf-options '{ "format":"a4", "printBackground":true }' `
           --stylesheet ./styles/markdown-pdf.css `
           --stylesheet ./styles/vscode.css `
           --stylesheet ./styles/markdown.css `
           --stylesheet ./styles/tomorrow.css `
           ./mds/*.md
          cp ./mds/*.pdf ./pdfs/
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs