
name: "Try"
on:
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
      csv:
        description: 'csv'
        required: false
        type: string
      stage:
        description: 'stage'
        required: false
        type: string
        default: main

jobs:
  job1:
    environment: distro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: https://mdsol.jfrog.io/
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_PREPROD_PASSWORD }}
          # JF_USER: ${{ secrets.ARTIFACTORY_PREPROD_USERNAME }}
          # JF_PASSWORD: ${{ secrets.ARTIFACTORY_PREPROD_PASSWORD }}
      - run: |
          echo "${{ github.run_number }}" > ${{ github.run_number }}.txt
          jfrog rt u --user ${{ secrets.ARTIFACTORY_PREPROD_USERNAME }} --password ${{ secrets.ARTIFACTORY_PREPROD_PASSWORD }} --url https://mdsol.jfrog.io/artifactory --flat=true "*" raveedc-generic-dev-local/ci/artifacts/apps/test/