
name: "Try Extract"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  pull_request:
    types: [synchronize]
  # issue_comment:
  #   types: [created]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          Write-Host "${{ github.event_name }}"
          Write-Host "pr ? ${{ github.event.pull_request }}"
        shell: pwsh

      # - uses: khan/pull-request-comment-trigger@v1.1.0
      #   id: check
      #   with:
      #     trigger: 'check pr'
      #     reaction: rocket
      #     prefix_only: true

      # - uses: actions/checkout@v3
      #   if:  ${{ github.event_name == 'pull_request' || steps.check.outputs.triggered == 'true' }}

      - id: extract
        if:  ${{ github.event_name == 'pull_request' || steps.check.outputs.triggered == 'true' }}
        uses: begedin/variable-regex-extractor-action@v0.2.1
        with:
          pattern: |
            RaveDB:\s*([\w\-_\.\/]+)

      - run: |
          Write-Host "value = $env:value"
        shell: pwsh
        if:  ${{ github.event_name == 'pull_request' || steps.check.outputs.triggered == 'true' }}
        env: 
          value: ${{ steps.extract.outputs.value }}

