
name: "Try"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
      csv:
        description: 'csv'
        required: false
        type: string
      stage:
        description: 'stage'
        required: false
        type: string
        default: main
jobs:
  job1:
    runs-on: "${{ inputs.stage == 'lab1' && 'lab1' || 'ubuntu-latest' }}"
    steps:
      - uses: jfrog/setup-jfrog-cli@v4
        env:
            JF_URL: https://mdsol.jfrog.io
            JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - id: try
        run: |
          $Env:CSV
        shell: pwsh
        env:
          INPUTS_RAVE_DB_REF2: ${{ env.INPUTS_RAVE_DB_REF }}
          INPUTS_RAVE_DB_REF: ${{ inputs.rave-db-ref }}
          CSV: ${{ inputs.csv }}
