
name: "Try"
run-name: "Try run-name: ${{ github.env.GITHUB_SHA_SHORT}}"
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
      yaml:
        description: 'yaml'
        required: false
        type: string
      stage:
        description: 'stage'
        required: false
        type: environment
        default: main
      foo:
        description: 'foo boolean'
        required: false
        type: boolean
      foo1:
        description: 'foo boolean'
        required: false
        type: boolean
      foo2:
        description: 'foo boolean'
        required: false
        type: boolean        
      foo3:
        description: 'foo boolean'
        required: false
        type: boolean
      foo4:
        description: 'foo boolean'
        required: false
        type: boolean

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls env:
        shell: pwsh

