name: Test Check Artifacts

on:
  workflow_dispatch:
jobs:
  check:
    outputs:
      search-exist: ${{ steps.search.outputs.exists }}
    runs-on: ubuntu-latest
    name: Download and deploy artifact for some application
    steps:
      - name: Setup JFrog Artifactory CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://mdsol.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_PREPROD_PASSWORD }}
      - id: search
        name: Search artifacts
        run: |
          jfrog rt s "raveedc-generic-preprod-local/artifacts/apps/raveedc/*390cfc97*/" --count
          $exists = [int]$count -gt 0
          "count=$count" | Add-Content -Path $env:GITHUB_OUTPUT
          "exists=$($exists.ToString().ToLower())" | Add-Content -Path $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Found artifact
        if: steps.search.outputs.exists == 'true'
        run: echo "Artifact exists"

      - name: Print count
        run: echo "${{ steps.search.outputs.count }}"