name: Debug Runner

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: Runs on
        required: true
        type: choice
        options:
        - '"rave-ci-lab1"'
        - '"rave-ci-hdc"'
        - '["self-hosted", "ubuntu-latest"]'
jobs:
  sleep-infinity:
    name: Start Runner and hang
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Sleep infinity
        id: sleep-infinity
        run: sleep infinity
        shell: bash