
name: "Try labeled"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: try
        run: |
          $PRNumber = $Env:GITHUB_EVENT_PULL_REQUEST_NUMBER
          Write-Host $env:PRNumber
        shell: pwsh
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
