name: Test PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
jobs:
  test-trigger:
    name: Start Runner and hang
    runs-on: ubuntu-latest
    steps:
      - name: Test0
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'need e2e')
        run: |
          Write-Host "Labels: ${{ toJson(github.event.pull_request.labels) }}"
        shell: pwsh
