name: Test Check Artifacts

on:
  workflow_dispatch:
jobs:
  check:
    outputs:
      status: ${{ steps.existance-check.outputs.artifact_exists }}
    runs-on: ubuntu-latest
    name: Download and deploy artifact for some application
    steps:
      - id: existance-check
        uses: telia-actions/check-artifact-existence-in-jfrog@v1
        with:
          jfrog-repo-name: 'https://mdsol.jfrog.io'
          jfrog-username: ${{ secrets.ARTIFACTORY_PREPROD_USERNAME }}
          jfrog-password: ${{ secrets.ARTIFACTORY_PREPROD_PASSWORD }}
          search-phrase: raveedc-generic-preprod-local/artifacts/apps/raveedc/*cc27c659*/