
name: "Try"
on:
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
      yaml:
        description: 'yaml'
        required: false
        type: string
      stage:
        description: 'stage'
        required: false
        type: string
        default: main

jobs:
  job1:
    environment: distro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: mds
          output_dir: pdfs
      - run: |
          Get-ChildItem . -Recurse
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs