
name: "Try"
on:
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
      yaml:
        description: 'yaml'
        required: false
        type: string
      stage:
        description: 'stage'
        required: false
        type: string
        default: main

jobs:
  job1:
    environment: distro
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $yaml
        env:
          yaml: ${{ inputs.yaml }}