name: Test PR

on:
  pull_request:
jobs:
  test-trigger:
    name: Start Runner and hang
    runs-on: ubuntu-latest
    steps:
      - name: Test
        id: test
        run: echo ${{ github.event.pull_request.labels }}
        shell: bash