
name: "Try"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
jobs:
  job1:
    runs-on: arc-runner-linux
    steps:
      - uses: jfrog/setup-jfrog-cli@v4
        env:
            JF_URL: https://mdsol.jfrog.io
            JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - id: try
        run: |
          New-Item -ItemType Directory ${{ runner.temp }}/_tmp/reports/1
          New-Item -ItemType Directory ${{ runner.temp }}/_tmp/reports/2
          @{ a = 1 } | ConvertTo-Json | Out-File ${{ runner.temp }}/_tmp/reports/1/a.result.json
          @{ b = 2 } | ConvertTo-Json | Out-File ${{ runner.temp }}/_tmp/reports/2/b.result.json
          Write-Host "KUBERNETES_SERVICE_NODE_NAME = $env:KUBERNETES_SERVICE_NODE_NAME"
        shell: pwsh
        env:
          INPUTS_RAVE_DB_REF2: ${{ env.INPUTS_RAVE_DB_REF }}
          INPUTS_RAVE_DB_REF: ${{ inputs.rave-db-ref }}
