name: Test PR

on:
  workflow_dispatch:
jobs:
  test-single-runner:
    name: Test Single Runner
    uses: ./.github/workflows/test-runs-on.yml
    with:
      runs-on: ubuntu-latest
  
  test-multiple-runners:
    name: Test Multiple Runners (Array Format)
    uses: ./.github/workflows/test-runs-on.yml
    with:
      runs-on-array: '["ubuntu-latest", "linux"]'
