
name: "Try"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
      csv:
        description: 'csv'
        required: false
        type: string
      stage:
        description: 'stage'
        required: false
        type: string
        default: main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: get-scaleset-name
        name: Setup Prod Nuget Source
        uses: ./.github/actions/get-scaleset-name
        with:
          stage: sts
      - run: Write-Host "scaleset name = ${{ steps.get-scaleset-name.outputs.scaleset }}"
        shell: pwsh