
name: "Try labeled"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  workflow_dispatch:
    inputs:
      rave-db-ref:
        description: 'RaveDB Reference, use commit hash, branch name or tag'
        required: false
        type: string
        default: main
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'docs/**'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: try
        run: |
          if ([string]::IsNullOrEmpty($Env:PR_NUMBER))
          {
            $ravedbRef = $Env:INPUTS_RAVE_DB_REF
          }
          else
          {
            $body = gh pr view https://github.com/$Env:GITHUB_REPOSITORY/pull/$Env:PR_NUMBER -q '.body' --json body
            $ravedbRef = [Regex]::match($body, 'RaveDB: \s*([\w\-_\.\/]+)').Groups[1].Value
          }
          Write-Host $ravedbRef
        shell: pwsh
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          INPUTS_RAVE_DB_REF: ${{ inputs.rave-db-ref }}
