name: Hello example reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'who to greet'
        default: 'some random guy'
        required: true
        type: string
jobs:
  say-hello:
    name: Say hello
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: |
          echo "Hello0! ${{ github.event.inputs.who-to-greet }}"
          echo "Hello1! ${{ inputs.who-to-greet }} "
        shell: pwsh
        
  api-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          repository: mdsol/rave_ci
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: .github/rave_ci

      - name: api checkout
        uses: mdsol/rave_ci/actions/update-cyclops2-databag@api-checkout
        with:
          repository: mdsol/RaveEDC
          out-directory: ${{ runner.temp }}
          paths: |
            cd/cyclops
            cd/github_functions.psm1
            cd/manifests_functions.psm1
            manifests
            pir
          refs: develop
          github-token: ${{ secrets.PERSONAL_TOKEN }}