
name: Build
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'doge'
jobs:
  job1:
    uses: ./.github/actions/hello.yml
    with:
      who-to-greet: ${{ github.event.inputs.who-to-greet }}
