
name: Build
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'doge'
env:
  env0: abc
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: |
            cd
            PIR.txt
          path: ${{ runner.temp }}
          ref: a0d73a2ae98412f10180f2000c0ba5f28e82f7c7
      - run: |
          ls -alF
          ls cd -alF
        working-directory: ${{ runner.temp}}



