
name: Build
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref'
        required: false
        default: ''
      gambit-deploy-tag:
        description: "Gambit: <url> | <template>, this overrides manifest json"
        required: false
        default: ''
      dss-deploy-tag:
        description: "DSS: <url> | <template>, this overrides manifest json"
        required: false
        default: ''
      slaad-deploy-tag:
        description: "Slaad: <url> | <template>, this overrides manifest json"
        required: false
        default: ''
      rave-deploy-tag:
        description: "Rave: <url> | <template>, this overrides manifest json"
        required: false
        default: ''
      json:
        description: "Json"
        default: ''

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Partial Checkout
        run: |
          $files = @(".github/actions/gitapi-checkout/action.yml", ".github/actions/gitapi-checkout/functions.psm1")
          $files | ForEach-Object {
              $ref = $Env:GITHUB_REF -replace 'refs/heads/', ''
              $api = "https://api.github.com/repos/$Env:GITHUB_REPOSITORY/contents/$_`?ref=$ref"
              $url = gh api $api --jq .download_url
              $dir = Split-Path $_
              New-Item -Path $dir -ItemType Directory -Force | Out-Null
              Invoke-WebRequest $url -OutFile $_
          }
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/gitapi-checkout
        with:
          paths: |
            .github
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          @"
          ${{ github.event.inputs.json }}
          "@ | test-json
          $json = @"
          ${{ github.event.inputs.json }}
          "@
          $json = $json | ConvertFrom-Json
          $json
        shell: pwsh


