
name: "Build : Build 1"
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        options:
        - sandbox
        - distro
        - UAT
      targetBranch:
        description: 'target branch'
        required: true
        default: '' 
jobs:
  call-workflow:
    uses: ./.github/workflows/hello.yml
    with:
      who-to-greet: "Mike"
  job1:
    api-checkout:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout actions
          uses: actions/checkout@v3
          with:
            repository: mdsol/rave_ci
            token: ${{ secrets.PERSONAL_TOKEN }}
            path: .github/rave_ci
            ref: api-checkout

        - name: api checkout
          uses: ./.github/rave_ci/actions/update-cyclops2-databag
          with:
            repository: mdsol/RaveEDC
            out-directory: ${{ runner.temp }}
            paths: |
              cd/cyclops
              cd/github_functions.psm1
              cd/manifests_functions.psm1
              manifests
              pir
            refs: develop
            github-token: ${{ secrets.PERSONAL_TOKEN }}



