
name: Build
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref'
        required: false
        default: ''
env:
  env0: abc
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: |
            .github
      - name: Git Api checkout
        uses: ./.github/actions/gitapi-checkout
        with:
          out-directory: "test-out"
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          paths: |
            cd
            scripts
            docker
      - run: ls test-out


