
name: Build
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'doge'
jobs:
  job1:
    uses: chenghuang-mdsol/test-github-action/.github/workflows/hello.yml@v1
    with:
      who-to-greet: ${{ github.event.inputs.who-to-greet }}
