
name: "Build : Build 1"
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
    inputs:
      script:
        description: 'script'
        required: true
        default: 1.ps1
        type: choice
        options:
        - 1.ps1
        - 2.ps1
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        options:
        - sandbox
        - distro
        - UAT
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          Write-Host "${{ inputs.script }}"
        shell: pwsh

