
name: "Build : Build 1"
on:
  workflow_dispatch:
    inputs:
      script:
        description: 'script'
        required: true
        default: 1.ps1
        type: choice
        options:
        - 1.ps1
        - 2.ps1
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        options:
        - sandbox
        - distro
        - UAT
jobs:
  # call-workflow:
  #   name: "Hello workflow"
  #   uses: ./.github/workflows/hello.yml
  #   with:
  #     who-to-greet: "Mike"

  api-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Checkout actions
      #   uses: actions/checkout@v2
      #   with:
      #     repository: mdsol/rave_ci
      #     token: ${{ secrets.PERSONAL_TOKEN }}
      #     path: .github/rave_ci

      # - name: api checkout
      #   uses: ./.github/rave_ci/actions/api-checkout
      #   with:
      #     repository: mdsol/RaveEDC
      #     out-directory: ${{ runner.temp }}
      #     paths: |
      #       cd/cyclops
      #       cd/github_functions.psm1
      #       cd/manifests_functions.psm1
      #       manifests
      #       pir
      #     refs: develop
      #     github-token: ${{ secrets.PERSONAL_TOKEN }}
      - name: 1.ps1 => exit 1, 2.ps1 => exit 0
        run: |
          if ( '${{ github.event.inputs.script }}' -eq '1.ps1' )
          {
            ./1.ps1
          }
          else
          {
            ./2.ps1
          }
        shell: pwsh

