
name: "Build : Build 1"
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        options:
        - sandbox
        - distro
        - UAT
      targetBranch:
        description: 'target branch'
        required: true
        default: '' 
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          Get-ChildItem Env:
        shell: pwsh
      - run: |
          Write-Host "logLevel == ${{ github.event.inputs.logLevel }}"
          Write-Host "tags == ${{ github.event.inputs.tags }}"
          Write-Host "environment == ${{ github.event.inputs.environment }}"
        shell: pwsh

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: 'true'
          submodules: recursive
          ssh-strict: false
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: source


      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.targetBranch }}
          clean: 'true'
          submodules: recursive
          ssh-strict: false
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: target

      - run: |
          ls .
          Push-Location source
          git rev-parse --abbrev-ref HEAD
          Pop-Location
          Push-Location target
          git rev-parse --abbrev-ref HEAD
          Pop-Location
        shell: pwsh