
name: "Build : Build 1"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: sandbox
      test:
        description: 'Test input'
        required: false
        type: string

jobs:
  call_cerebro:
    uses: ./.github/workflows/cerebro.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
