
name: "Build : Build 1"
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          Get-ChildItem Env:
        shell: pwsh
      - run: |
          Write-Host "logLevel == ${{ github.event.inputs.logLevel }}"
          Write-Host "tags == ${{ github.event.inputs.tags }}"
          Write-Host "environment == ${{ github.event.inputs.environment }}"
        shell: pwsh


