
name: Build
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref'
        required: false
        default: ''
      test-param:
        description: 'test parameter'
        required: false
        default: ''

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        with:
          patterns: |
            .github
      - run: |
          $json = (Get-Content -Raw -Path $Env:GITHUB_EVENT_PATH  | ConvertFrom-Json)
          $json
        shell: pwsh


