
name: "Build : Build 1"
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref'
        required: false
        default: ''
      gambit-deploy-tag:
        description: "Gambit: <url> | <template>, this overrides manifest json"
        required: false
        default: ''
      dss-deploy-tag:
        description: "DSS: <url> | <template>, this overrides manifest json"
        required: false
        default: ''
      slaad-deploy-tag:
        description: "Slaad: <url> | <template>, this overrides manifest json"
        required: false
        default: ''
      rave-deploy-tag:
        description: "Rave: <url> | <template>, this overrides manifest json"
        required: false
        default: ''
      json:
        description: "Json"
        default: ''

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          Get-ChildItem Env:
        shell: pwsh


