
name: "Build : Build 1"
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
    inputs:
      script:
        description: 'script'
        required: true
        default: 1.ps1
        type: choice
        options:
        - 1.ps1
        - 2.ps1
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        options:
        - sandbox
        - distro
        - UAT
jobs:
  echo-in-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dependencies
        uses: mdsol/QuicksilverActions/actions/setup@144a712ae87eec1e5932816fa37277c21aec92ea
        with:
          artifactory-username: ${{ secrets.ARTIFACTORY_PREPROD_USERNAME }}
          artifactory-password: ${{ secrets.ARTIFACTORY_PREPROD_PASSWORD }}
          dotnet-version: |
            6.0.202
            7.0.100


