
name: "Build : Build 1"
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
    inputs:
      script:
        description: 'script'
        required: true
        default: 1.ps1
        type: choice
        options:
        - 1.ps1
        - 2.ps1
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: sandbox
        options:
        - sandbox
        - distro
        - UAT
      test:
        description: 'Test input'
        required: false
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        shell: bash
  call_cerebro:
    needs: [job1]
    uses: ./.github/workflows/cerebro.yml
    with:
      deployment-manifests: ${{ needs.job1.outputs.matrix }}
