
name: "Build : Build 1"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: sandbox
      test:
        description: 'Test input'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Post Action
      id: test-pwsh
      uses: srz-zumix/post-run-action@v1
      with:
        shell: pwsh
        post-run: |
          $arr = 1..8
          foreach($a in $arr)
          {
            Write $a
          }
    - name: Shell command
      run: |
        Write-Host "Some command"
      shell: pwsh
