
name: Build
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'doge'
env:
  env0: abc
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files
        with:
          files: cd/functions.psm1
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          ls -alF
          ls cd -alF


