
name: "Build : Build 1"
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
    inputs:
      script:
        description: 'script'
        required: true
        default: 1.ps1
        type: choice
        options:
        - 1.ps1
        - 2.ps1
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: sandbox
        options:
        - sandbox
        - distro
        - UAT
      test:
        description: 'Test input'
        required: false
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env: 
      testEnv: ${{ inputs.test || 'abc' }}
    steps:
      - name: test env
        run: |
          Write-Host "$Env:testEnv"
        shell: pwsh

