
name: "Build : Build 1"
env:
  GITHUB_TOKEN: ${{ secrets.EXTERNAL_GITHUB_TOKEN }}
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: sandbox
      test:
        description: 'Test input'
        required: false
        type: string

jobs:
  create-matrix:
    runs-on: [ubuntu-latest, linux]
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Generate Matrix JSON
        id: generate-matrix
        run: |
          # Generate JSON matrix and save as output
          echo '{"include":[{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":0},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":1},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":2},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":3},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":4},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":5},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":6},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":7},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":8},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":9},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":10},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":11},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":12},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":13},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":14},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":15},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":16},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":17},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":18},{"QueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8","ResultQueueName":"rg-test-110-96af3a96-6f69-4139-8356-e6b9ef138fc8-result","AgentID":19}]}' > matrix.json
          MATRIX_JSON=$(cat matrix.json)
          echo "::set-output name=matrix::$MATRIX_JSON"
      
  consume-matrix:
    needs: create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.create-matrix.outputs.matrix) }}
    # env:
    #   QUEUE_NAME: ${{ matrix.QueueName }}
    #   RESULT_QUEUE_NAME: ${{ matrix.ResultQueueName }}
    steps:
      - name: Show Matrix Data
        run: |
          echo "Running job for name: ${{matrix.QueueName}} with value: ${{matrix.ResultQueueName}}"
