
name: Build
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'doge'
jobs:
  job1:
    name: Job1
    uses: chenghuang-mdsol/test-github-action/.github/workflows/hello.yml@master
    with:
      who-to-greet: ${{ github.event.inputs.who-to-greet }}
  job2:
    name: Job2
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is job 2"

