
name: "Build : Build 1"
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:
    inputs:
      script:
        description: 'script'
        required: true
        default: 1.ps1
        type: choice
        options:
        - 1.ps1
        - 2.ps1
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        options:
        - sandbox
        - distro
        - UAT
jobs:
  api-checkout:
    runs-on: [self-hosted]
    steps:
      - name: add env
        run: |
          "envvar1=123" | Out-File -Append -FilePath $Env:GITHUB_ENV
          Write-Host $Env:GITHUB_ENV
          Get-Content $Env:GITHUB_ENV
        shell: pwsh

      - name: test env
        run: |
          Write-Host "envvar1=$env:envvar1"
          Get-ChildItem env: | Format-Table -AutoSize
          Get-Content $Env:GITHUB_EVENT_PATH
          Get-Content $Env:GITHUB_ENV
          
          "# Abc" | Out-File -Append $env:GITHUB_STEP_SUMMARY 
        shell: pwsh

