on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
jobs:
  output-pr-event:
    name: Cyclops Url
    runs-on: ubuntu-latest
    steps:
      - name: Debug inputs
        run: |
          Get-Content $env:GITHUB_EVENT_PATH | Out-File event.json
        shell: pwsh
      - uses: actions/upload-artifact@v7
        with:
          name: event.json
          path: event.json
